[package]
name = "pawn-amx"
version = "0.1.0"
edition = "2024"
description = "AMX (Abstract Machine eXecutor) runtime for Pawn"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
